Repository Rickz75/bende, pull requests merged in 2022-04, with the labels that each got.

#1 Enhancement/option support
  Cargo.toml
  README.md
  src/de.rs
  src/en.rs
  src/lib.rs
Labels: enhancement

#4 Fix/units and newtypes
  Cargo.toml
  src/de.rs
  src/en.rs
  src/lib.rs
Labels: bug

#5 Fix/string only keys
  Cargo.toml
  README.md
  src/de.rs
  src/en.rs
Labels: bug, enhancement

#7 Feat/sorted dict
  Cargo.toml
  README.md
  src/en.rs
  src/lib.rs
Labels: bug, enhancement

#8 Feature: A Value type
  Cargo.toml
  README.md
  src/lib.rs
  src/value.rs
Labels: enhancement

#9 Feat/value methods
  Cargo.toml
  README.md
  src/value.rs
Labels: enhancement
